### PR TITLE
fix: Make ActsSimGeantinoRecordingDD4hep less verbose

### LINKED ISSUE #730: ActsSimGeantinoRecordingDD4hep is too verbose
Anyone who has ever run the `ActsSimGeantinoRecordingDD4hep` example with default parameters + OpenDataDetector input can attest that it is a remarkably effective way of losing your terminal history, unless you have set up your terminal for very large / unlimited buffering and made sure it's actually good enough at scrolling into a very long history.

Indeed, that example produces no less than 116746 lines of log during initialization. If you put that into a file, that's >13MB of text.

99.1% of that log (approx. 115.8k lines) comes from a single source, which is DD4hep's `Geant4Converter`. The purpose of this tool should be rather clear from its name: it takes a DD4hep geometry and turns it into a Geant4 one for simulation purposes. However, it would be nice if it were just a little less talkative in the process.

The Geant4Converter log, in turn, contains several different things, including relatively interesting and condensed info about the Geant4 settings used for translated material for example. But this small bit of info is drowned in a sea of almost always irrelevant details about how DD4hep translated every single detector element into its Geant4 equivalent, going down to the memory addresses at which each element of the original geometry and its Geant4 translation lie, and detailing every step from shape (surface/volume) and material translation to the positioning of every element in the final geometry. The latter accounts for the bulk of the log volume, as individual shapes are copied many times across a single geometry.

Now, in my opinion, part of the problem must be resolved on the DD4hep side here, in the sense that we're only configuring the Geant4Converter at `INFO` log level, and even though the semantics of log levels are highly subjective and open to endless debate, I think most people should agree that this level of detail belongs to a higher verbosity level, at least `DEBUG` and probably `VERBOSE` in our classification. Hence I'll open a companion bug report in their repository.

But since DD4hep's build system is what it is, people tend to stick to whatever old version they managed to get to work someday, which means that any fix that I convince upstream of accepting will not help the people who run our examples into a long while. Therefore, I think it might also be a good idea to reduce the log level that we request from DD4hep's Geant4Converter on our side.

What do you think?

### PR DESCRIPTION
**Pull request by HadrienG2**
Fixes #730 . I now consider this to be a clean fix.

### CODE REVIEW

**Comment by HadrienG2** [comment]
@Corentin-Allaire This now implements your suggestion from #730 . Thanks !

File: Examples/Algorithms/Geant4DD4hep/src/DD4hepDetectorConstruction.cpp [hunk 1]
```diff
@@ -25,7 +26,7 @@ DD4hepDetectorConstruction::DD4hepDetectorConstruction(
 G4VPhysicalVolume* DD4hepDetectorConstruction::Construct() {
   dd4hep::sim::Geant4Mapping& g4map = dd4hep::sim::Geant4Mapping::instance();
   dd4hep::DetElement world = m_detector.world();
-  dd4hep::sim::Geant4Converter conv(m_detector, dd4hep::INFO);
+  dd4hep::sim::Geant4Converter conv(m_detector, dd4hep::PrintLevel::VERBOSE);
```
Comment (Corentin-Allaire) [inline Examples/Algorithms/Geant4DD4hep/src/DD4hepDetectorConstruction.cpp:29]: Since the log level would have already been defined globally in the DD4hepGeometryService could'nt you just use : `dd4hep::sim::Geant4Converter conv(m_detector);` ?

**Review by Corentin-Allaire — COMMENTED** [review]
Looks good to me (But I will admit not being the biggest DD4Hep expert).

File: Examples/Algorithms/Geant4DD4hep/src/DD4hepDetectorConstruction.cpp (hunk 1 above)
Comment (HadrienG2) [reply Examples/Algorithms/Geant4DD4hep/src/DD4hepDetectorConstruction.cpp:29]: These two settings actually do two different things, because DD4hep logging [does not follow the same logic as our logging](https://github.com/acts-project/acts/issues/730#issuecomment-787727102):

- The log level that is being set here in the `DD4hepDetectorConstruction` dictates at which log level messages related to the `Geant4Converter` will be emitted inside of DD4hep.
- The log level that is being set in the `DD4hepGeometryService` dictates what is DD4hep's logging threshold, that is, what is the minimal log level that a message must have for DD4hep to print it.

Comment (Corentin-Allaire) [reply Examples/Algorithms/Geant4DD4hep/src/DD4hepDetectorConstruction.cpp:29]: I reread #730 afterward and understood after asking this. Sorry and thanks for explaining again.

**Review by Corentin-Allaire — APPROVED** [review]
