### PR TITLE
fix: Move Geant4 actions into namespaces

### LINKED ISSUE #874: Geant4 actions are duplicated
We have duplicate classes like `PrimaryActionGenerator`, one in Geant4 and one in Geant4HepMC3 examples. Is this on purpose/necessary?

### PR DESCRIPTION
**Pull request by paulgessinger**
Previously these had the same symbol names between ExamplesGeant4 and ExamplesGeant4HepMC3. This is fine if these libraries are never linked together, but if that happens, it leads to crashes due to incompatible clashes. This moves both sets of classes into namespaces, to avoid clashes.

Fixes #874

/cc @FabianKlimpel

### CODE REVIEW

File: Examples/Algorithms/Geant4/src/GeantinoRecording.cpp [hunk 1]
```diff
@@ -22,6 +22,7 @@
 #include "SteppingAction.hpp"
 
 using namespace ActsExamples;
+using namespace ActsExamples::Geant4;
```
Comment (FabianKlimpel) [inline Examples/Algorithms/Geant4/src/GeantinoRecording.cpp:25]: Is it safe to use it here?

File: Examples/Algorithms/Geant4HepMC/src/EventRecording.cpp [hunk 2]
```diff
@@ -16,6 +16,8 @@
 #include <stdexcept>
 
 #include <FTFP_BERT.hh>
+#include <G4RunManager.hh>
+#include <G4VUserDetectorConstruction.hh>
```
Comment (FabianKlimpel) [inline Examples/Algorithms/Geant4HepMC/src/EventRecording.cpp:20]: Isn't this already included from the header?

**Review by FabianKlimpel — COMMENTED** [review]
Pretty uncontroversal, I just have two minor question. Other than that it's good as it is

File: Examples/Algorithms/Geant4/src/GeantinoRecording.cpp (hunk 1 above)
Comment (paulgessinger) [reply Examples/Algorithms/Geant4/src/GeantinoRecording.cpp:25]: Ah yes. I think this should be safe here. I'm doing this here because `GeantinoRecording` is not inside the `Geant4` namespace. This could also be changed, but I think all other algorithms are directly in `ActsExamples`.

File: Examples/Algorithms/Geant4HepMC/src/EventRecording.cpp (hunk 2 above)
Comment (paulgessinger) [reply Examples/Algorithms/Geant4HepMC/src/EventRecording.cpp:20]: It's probably not strictly necessary, but doesn't hurt to have. I think I added this for the python bindings, and didn't remove for this PR. 

I can strip these if you prefer.

Comment (FabianKlimpel) [reply Examples/Algorithms/Geant4HepMC/src/EventRecording.cpp:20]: I fine with both and I don't want to block this trivial PR by this detail.

**Review by FabianKlimpel — APPROVED** [review]
